import Head from "next/head";
import LoadBtn from "../components/button/loadBtn";
import TextCard from "../components/cards/textCard/textCard";
import ImgCard from "../components/cards/imgCard/imgCard";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";
import Card from "../components/cards/card/card";
import Sidebar from "../components/sidebar/sidebar";
import Post from "../components/posts";
import { getPosts } from "../utils/wordpress";

export default function Home({posts}) {
  const featuredImage = posts[0]._embedded['wp:featuredmedia'][0].source_url
  const jsxPosts = posts.map((post) => {
    return <Post post={post} key={post.id} />;
  });
  // console.log(posts[0] )
  return (
    <>
      <Head>
        <title>Contentberg NextJS Theme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container">
        <div className="homeSection">
          <div className="featSection">
            <ImgCard posts={posts[0]}/>
            <div>
              <h3 className="blockHeader">More Featured</h3>
              <div className="postList">
            {posts.slice(1,5).map((post) => {
    return <TextCard post={post} key={post.id} />;
  })}
              </div>
            </div>
          </div>
        </div>
        <div className="homeSection">
          <div className="sectionTitle">
            <h2>News &amp; Rumours</h2>
            <span className="meta">View all</span>
          </div>
          <div className="twoCol">
          <ImgCard posts={posts[1]}/>
          <ImgCard posts={posts[2]}/>
          </div>
          <LoadBtn />
        </div>
        <div className="homeSection">
          <div className="sectionTitle">
            <h2>Marketing</h2>
            <span className="meta">View all</span>
          </div>
          <div className="threeCol">
          {posts.slice(2,8).map((post) => {
    return <ImgCard posts={post} key={post.id} />;
  })}
          </div>
          <LoadBtn />
        </div>
        <div className="homeSection">
          <div className="sectionTitle">
            <h2>Gadgets</h2>
            <span className="meta">View all</span>
          </div>
          <div className="twoCol">
            <div className="leftCol">
              <ImgCard posts={posts[8]} />
            </div>
            <div className="rightCol">
            {posts.slice(9,13).map((post) => {
    return <Card post={post} key={post.id} />;
  })}
            </div>
          </div>
        </div>
        <div className="homeSection">
          <div className="sectionTitle">
            <h2>News &amp; Rumours</h2>
            <span className="meta">View all</span>
          </div>
          <div className="twoCol">
          {posts.slice(13,15).map((posts) => {
    return <ImgCard posts={posts} key={posts.id} />;
  })}
          </div>
          <LoadBtn />
        </div>
        <div className="homeSection">
          <div className="withSidebar">
            <div className="leftCol">
              <div className="sectionTitle">
                <h2>What&apos;s New?</h2>
                <span className="meta">View all</span>
              </div>
              {posts.slice(15,20).map((posts) => {
    return <ImgCard posts={posts} key={posts.id} />;
  })}
            </div>
            <div className="rightCol">
              <Sidebar />
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
export async function getStaticProps({ params }) {
  const posts = await getPosts();

  return {
    props: {
      posts    },
    revalidate: 10, // In seconds
  };
}